import { ContentLayout } from "components/ContentLayout";
import Head from "next/head";
import React from "react";
import styles from "styles/Content.module.css";

export default function BoxViewGuide() {
  return (
    <>
      <Head>
        <title>Box View Explainer | Guides</title>
        <meta
          name="description"
          content="How the Soullocke Box view works: drag-and-drop management of your team, box, daycare, and grave, the 6-Pokémon team limit, renaming, and quick-adding catches."
        />
      </Head>
      <ContentLayout
        title="Box View Explainer"
        description="The Box tab is your PC: every soul link in the run, laid out in four sections — Team, Box, Daycare, and Grave — with each entry showing both trainers' Pokémon together, because linked Pokémon always travel together."
      >
        <section className={styles.section}>
          <h2 className={styles.sectionTitle}>Moving pairs: just drag</h2>
          <p className={styles.body}>
            Drag a pair from one section and drop it in another. Bookkeeping
            is automatic for you:
          </p>
          <ul className={styles.list}>
            <li>
              Both trainers&apos; Pokémon move at once (a link is never
              split).
            </li>
            <li>
              A &quot;moved&quot; event is logged on each Pokémon&apos;s
              history automatically.
            </li>
          </ul>
          <p className={styles.body}>Two things to know:</p>
          <ul className={styles.list}>
            <li>
              <strong>The 6-Pokémon team limit is enforced.</strong> Dropping
              a seventh pair onto Team is rejected with a warning. Move a pair
              out first — or use the Timeline&apos;s Move flow, which offers a
              one-step swap instead.
            </li>
            <li>
              <strong>There&apos;s no reordering within a section</strong> —
              drops inside the same section do nothing.
            </li>
          </ul>
        </section>

        <section className={styles.section}>
          <h2 className={styles.sectionTitle}>Finding and fixing Pokémon</h2>
          <ul className={styles.list}>
            <li>
              <strong>Hover</strong> any Pokémon to see the pair&apos;s
              nicknames.
            </li>
            <li>
              <strong>Click</strong> a Pokémon to open its card, where you can
              fix the species or edit nicknames (double-click the text to
              edit).
            </li>
            <li>
              Note the Box card is <strong>rename-only</strong> by design:
              deaths, evolutions, and other events can be generated by
              dragging from Box section to section. Or can be logged from the
              Timeline tab, where the full event history lives.
            </li>
          </ul>
        </section>

        <section className={styles.section}>
          <h2 className={styles.sectionTitle}>Quick-adding a catch</h2>
          <p className={styles.body}>
            The <strong>search box</strong> at the top filters by Pokémon or
            location name, and the <strong>+</strong> button next to it logs a
            new catch without leaving the Box:
          </p>
          <ul className={styles.list}>
            <li>
              Pick the location under <strong>&quot;Caught at:&quot;</strong>{" "}
              — or type a brand-new name to create a custom location on the
              fly (romhacks, split areas, house-rule slots).
            </li>
            <li>
              Fill in each trainer&apos;s Pokémon and nickname, and{" "}
              <strong>Add</strong>. The location and the whole link land on
              the timeline in one step.
            </li>
          </ul>
        </section>

        <section className={styles.section}>
          <h2 className={styles.sectionTitle}>When to use Box vs Timeline</h2>
          <p className={styles.body}>
            Box view is for <em>managing state</em>: rearranging teams between
            gyms, checking bench depth, seeing the whole run&apos;s links at a
            glance. If the main thing you care about is just the current state
            of the run, the Box view is your friend. The Timeline is for{" "}
            <em>logging history</em>: encounters, deaths, evolutions, badges.
          </p>
        </section>
      </ContentLayout>
    </>
  );
}
