/**
 * Mapping of Pokemon names from PokeApi to the name used by
 * Pokesprite. Pokesprite is used for pokemon images in the
 * Summary view.
 */

export const pokemonAlternativeNames = {
  "aegislash-shield": "aegislash",
  "araquanid-totem": "araquanid",
  "basculin-red-striped": "basculin",
  "darmanitan-standard-galar": "darmanitan-galar",
  "darmanitan-standard": "darmanitan",
  "darmanitan-zen-galar": "darmanitan-galar-zen",
  "deoxys-normal": "deoxys",
  "eiscue-ice": "eiscue",
  "giratina-altered": "giratina",
  "gourgeist-average": "gourgeist",
  "greninja-battle-bond": "greninja",
  "gumshoos-totem": "gumshoos",
  "indeedee-male": "indeedee",
  "indeedee-female": "indeedee",
  "keldeo-ordinary": "keldeo",
  "kommo-o-totem": "kommo-o",
  "landorus-incarnate": "landorus",
  "lurantis-totem": "lurantis",
  "lycanroc-midday": "lycanroc",
  "marowak-totem": "marowak",
  "meloetta-aria": "meloetta",
  "meowstic-male": "meowstic",
  "meowstic-female": "meowstic",
  "mimikyu-busted": "mimikyu",
  "mimikyu-totem-busted": "mimikyu",
  "mimikyu-totem-disguised": "mimikyu",
  "minior-blue-meteor": "minior-blue",
  "minior-green-meteor": "minior-green",
  "minior-indigo-meteor": "minior-indigo",
  "minior-orange-meteor": "minior-orange",
  "minior-violet-meteor": "minior-violet",
  "minior-yellow-meteor": "minior-yellow",
  "oricorio-baile": "oricorio",
  "pumpkaboo-average": "pumpkaboo",
  "raticate-totem-alola": "raticate-alola",
  "ribombee-totem": "ribombee",
  "rockruff-own-tempo": "rockruff",
  "salazzle-totem": "salazzle",
  "shaymin-land": "shaymin",
  "stunfisk-galar": "stunfisk-galar",
  "thundurus-incarnate": "thundurus",
  "togedemaru-totem": "togedemaru",
  "tornadus-incarnate": "tornadus",
  "toxtricity-amped": "toxtricity",
  "urshifu-rapid-strike": "urshifu-rapid-strike-gmax",
  "vikavolt-totem": "vikavolt",
  "wormadam-plant": "wormadam",
  "zacian-hero": "zacian",
  "zamazenta-hero": "zamazenta",
  "zygarde-50": "zygarde",
};
